// Copies the Pyodide runtime core from node_modules into public/pyodide/ so
// the live-python block loads it SAME-ORIGIN. Reasons this matters:
//   - the app's CSP is `script-src 'self'` — the old jsDelivr <script>/import
//     was silently blocked, so live-python never ran in production;
//   - same-origin assets work offline and need no CSP allowance.
// public/pyodide/ is git-ignored and regenerated by predev/prebuild, so the
// ~13MB never enters the repo.
import { mkdirSync, copyFileSync, existsSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const srcDir = dirname(require.resolve("pyodide/package.json"));
const outDir = join(here, "..", "public", "pyodide");

// The minimal runtime set. Individual Python packages (numpy, etc.) are
// fetched lazily by Pyodide at use-time; the core below is enough to boot the
// interpreter and run pure-Python code.
const FILES = [
  "pyodide.js", // UMD build — loaded via a <script> tag by LivePyBlock
  "pyodide.mjs",
  "pyodide.asm.js",
  "pyodide.asm.wasm",
  "pyodide.asm.mjs",
  "python_stdlib.zip",
  "pyodide-lock.json",
];

mkdirSync(outDir, { recursive: true });
let copied = 0;
let bytes = 0;
for (const f of FILES) {
  const src = join(srcDir, f);
  if (!existsSync(src)) continue; // optional files differ across versions
  copyFileSync(src, join(outDir, f));
  bytes += statSync(src).size;
  copied++;
}
console.log(`copy-pyodide: ${copied} files → public/pyodide/ (${(bytes / 1e6).toFixed(1)} MB)`);
